theme = "hugo-hero-theme"
baseURL = "http://atlaselectoral.tucuman.gov.ar/"
languageCode = "es"
title = "Atlas Electoral de Tucumán"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Gobierno de la Provincia de Tucumán - Atlas Electoral"
    meta_og_title = "Atlas Electoral de Tucumán"
    meta_og_type = "website"
    meta_og_url = "http://atlaselectoral.tucuman.gov.ar/"
    meta_og_image = ""
    meta_og_description = "AET"
    meta_twitter_card = "summary"
    meta_twitter_site = ""
    meta_twitter_creator = ""

[[menu.main]]
	name = "Historia Electoral"
	url = "/historia/"
    weight = 3

[[menu.main]]
    name = "Normativa"
    url = "/norma/"
    weight = 2

[[menu.main]]
    name = "Sobre el AET"
    url = "/aet/"
    weight = 1

[[menu.main]]
    name = "Contacto"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
