theme = "hugo-hero-theme"
baseURL = "https://atlaselectoral.github.io/"
languageCode = "en-us"
title = "Atlas Electoral de Tucumán"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Gobierno de la Provincia de Tucumán - Atlas Electoral"
    meta_og_title = "Atlas Electoral de Tucumán"
    meta_og_type = "website"
    meta_og_url = "https://atlaselectoral.github.io/"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "AET"
    meta_twitter_card = "summary"
    meta_twitter_site = ""
    meta_twitter_creator = ""

[[menu.main]]
	name = "Historia Electoral"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Normativa"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "Sobre el AET"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contacto"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
